artifact_location: file:C:/Users/rodol/Desktop/Projetos/wallmart forecasting/Wallmart-Sales-Forecasting/mlflow/temp/510014504473116242
creation_time: 1755581842808
experiment_id: '510014504473116242'
last_update_time: 1755581842808
lifecycle_stage: active
name: temp_linear_regression
