artifact_location: file:C:/Users/rodol/Desktop/Projetos/wallmart forecasting/Wallmart-Sales-Forecasting/mlflow/temp/356579783828563703
creation_time: 1755581842750
experiment_id: '356579783828563703'
last_update_time: 1755581842750
lifecycle_stage: active
name: temp_sarimax
