artifact_location: file:C:/Users/rodol/Desktop/Projetos/wallmart forecasting/Wallmart-Sales-Forecasting/mlflow/temp/204909333412525805
creation_time: 1755581842785
experiment_id: '204909333412525805'
last_update_time: 1755581842785
lifecycle_stage: active
name: temp_xgboost
