services:
  postgres:
    image: postgres:15
    container_name: walmart_postgres
    environment:
      POSTGRES_DB: walmart_forecasting
      POSTGRES_USER: walmart_user
      POSTGRES_PASSWORD: walmart_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - walmart_network

  mlflow:
    image: python:3.9-slim
    container_name: walmart_mlflow
    working_dir: /app
    command: >
      bash -c "pip install mlflow psycopg2-binary &&
               mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri postgresql://walmart_user:walmart_password@postgres:5432/walmart_forecasting"
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5000
    networks:
      - walmart_network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  walmart_network:
    driver: bridge

