artifact_location: file:C:/Users/rodol/Desktop/Projetos/wallmart forecasting/Wallmart-Sales-Forecasting/mlflow/temp/184879660370053570
creation_time: 1755581842764
experiment_id: '184879660370053570'
last_update_time: 1755581842764
lifecycle_stage: active
name: temp_lightgbm
