artifact_location: file:C:/Users/rodol/Desktop/Projetos/wallmart forecasting/Wallmart-Sales-Forecasting/mlflow/temp/0
creation_time: 1755581842743
experiment_id: '0'
last_update_time: 1755581842743
lifecycle_stage: active
name: Default
