# GitHub Pages Configuration - Jekyll Completely Disabled
# This ensures your custom index.html is used instead of README.md

# Site settings
title: Walmart Sales Forecasting Dashboard
description: ML-powered sales forecasting dashboard for Walmart South Atlantic Division
author: Your Name
email: your.email@example.com

# Completely disable Jekyll processing
# This ensures your custom index.html is used instead of README.md
exclude:
  - README.md
  - "*.md"
  - .nojekyll
  - _config.yml

# URL settings (update with your actual repository details)
url: "https://rodolfoh.github.io/Wallmart-Sales-Forecasting"
baseurl: "/Wallmart-Sales-Forecasting"

# Social media links
social:
  name: Your Name
  links:
    - https://github.com/RodolfoHelf
    - https://linkedin.com/in/yourusername
