# GitHub Pages Configuration - Jekyll Disabled
# This file configures the site to use custom HTML instead of Jekyll processing

# Site settings
title: Walmart Sales Forecasting Dashboard
description: ML-powered sales forecasting dashboard for Walmart South Atlantic Division
author: Your Name
email: your.email@example.com

# Completely disable Jekyll processing
# This ensures your custom index.html is used instead of README.md
exclude:
  - README.md
  - "*.md"
  - .nojekyll

# URL settings (update with your actual repository details)
url: "https://yourusername.github.io/your-repo-name"
baseurl: "/your-repo-name"

# Social media links
social:
  name: Your Name
  links:
    - https://github.com/yourusername
    - https://linkedin.com/in/yourusername
